name: deploy-web

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "_"
          password: ${{ secrets.HEROKU_API_KEY }}
          registry: registry.heroku.com/cw-magidash-web/web


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.heroku.com/cw-magidash-web/web:latest
