name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Deploy
        run: mvn compile jib:build
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  deploy-web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "_"
          password: ${{ secrets.HEROKU_API_KEY }}
          registry: registry.heroku.com/cw-magidash-web/web

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
